language: php

sudo: required

php:
  - 7.0

install:
  - composer self-update
  - '[[ -z "3.0.x" ]] || git clone -q --depth=1 https://github.com/phalcon/cphalcon.git -b 3.0.x'
  - '[[ ! -z "3.0.x" ]] || git clone -q --depth=1 https://github.com/phalcon/cphalcon.git'
  - '(cd cphalcon/build; bash install &>/dev/null && phpenv config-add ../tests/_ci/phalcon.ini &> /dev/null && cd ../..;)'
  - php -r 'echo \Phalcon\Version::get() . PHP_EOL;'
  - travis_retry composer install --no-interaction --prefer-source --dev

before_script:
  - composer dump-autoload -o

script:
  - mkdir -p build/logs
  - phpunit --bootstrap ./tests/bootstrap.php --configuration ./phpunit.xml --coverage-clover build/logs/clover.xml
