language: php

sudo: required

php:
  - 7.2
  - 7.3
  - 7.4

env:
  global:
    - CC="gcc"
    - ZEPHIR_VERSION="0.12.19"
    - ZEPHIR_PARSER_VERSION="master"
    - REPORT_COVERAGE=0
    - PATH="${HOME}/.composer/vendor/bin:${PATH}"
    - TRAVIS_COMMIT_LOG="$(git log --format=fuller -5)"
    - DEFAULT_COMPOSER_FLAGS="--no-interaction --no-ansi --no-progress --no-suggest"
  jobs:
    - PHALCON_VERSION="3.4.x"

install:
  - chmod -R 755 .ci/*
  - .ci/install-zephir.sh
  - .ci/install-phalcon.sh
  - php -v
  - php -r 'echo \Phalcon\Version::get() . PHP_EOL;'
  - php -m
  - travis_retry composer install --no-interaction --prefer-source --dev

before_script:
  - composer dump-autoload

script:
  - mkdir -p build/logs
  - vendor/bin/phpunit --bootstrap ./tests/bootstrap.php --configuration ./phpunit.xml --coverage-clover build/logs/clover.xml --verbose --debug

after_script:
  - php vendor/bin/coveralls -v

after_success:
  - coveralls
